# before:
#   hooks:
#     - go mod tidy
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64
    dir: cmd
    binary: pulsar
    ldflags: "-s -w -X github.com/srgsf/pulsar-telegraf-plugin/plugins/inputs/pulsar.version=${{.Tag}}-{{.ShortCommit}}-{{.CommitDate}}"

archives:
  - replacements:
      darwin: macos
      amd64: x86_64
    format_overrides:
     - goos: windows
       format: zip
    files:
     - plugin.conf

checksum:
  name_template: 'checksums.txt'
